### ISSUE TITLE
Adding dictionary will not asoociated or linked to the original language

### ISSUE THREAD

**Issue by jwtiyar** [silnrsi/oxttools#10]
Hey
I have created new spellchecker for ckb (Central Kurdish), But it will not link to central Kurdish which available in LibreOffice, it will create new language.
I created by this command:
`makeoxt -d WordList.txt -l "Central kurdish" -t rtl ckb Central_Kurdish_Spellchecker.oxt`
What I did wrong?

**Comment by DavidLRowe** [comment]
If I understand the issue, you are saying that LibreOffice already has an entry for Central Kurdish. If so, adding something different that also claims to be Central Kurdish may cause a problem, particularly if it uses a different script.

Can you tell me what you are choosing in LibreOffice writer to select Central Kurdish?

It seems that you are using Arabic script (based on the "rtl" in the command line).

Could you post four or five words from your word list here for me to use to investigate this issue?

Thanks!

**Comment by jwtiyar** [comment]
Hey david
The problem is when i add dictionary it will not be added to central kurdish of libreoffice it will behave like another language , when i add central kurdish after that libre shows two central kurdish not one.
this is a kurdish sentence:
چۆنی، ئەتوانین قسە بکەین.

**Comment by jwtiyar** [comment]
> 
> 
> If I understand the issue, you are saying that LibreOffice already has an entry for Central Kurdish. If so, adding something different that also claims to be Central Kurdish may cause a problem, particularly if it uses a different script.
> 
> Can you tell me what you are choosing in LibreOffice writer to select Central Kurdish?
> 
> It seems that you are using Arabic script (based on the "rtl" in the command line).
> 
> Could you post four or five words from your word list here for me to use to investigate this issue?
> 
> Thanks!

Any progress to make it work?

**Comment by DavidLRowe** [comment]
When I started looking at this, I ran into problems because I'm now using Python 3 and this script and libraries it calls are still on Python 2, so I need to address that issue first.

**Comment by jwtiyar** [comment]
> 
> 
> When I started looking at this, I ran into problems because I'm now using Python 3 and this script and libraries it calls are still on Python 2, so I need to address that issue first.

Ok, Thank you. 
Take your time.

**Comment by DavidLRowe** [comment]
When investigating this issue, I updated the code to Python 3 and made a new release.
Then I followed this procedure (on a Windows 10 machine):

(1) Get makeoxt.exe program for Windows
From the https://github.com/silnrsi/oxttools/releases page, release v0.3, download makeoxt.zip and extract the makeoxt.exe file to a working folder.

(2) Construct LibreOffice extension with spell checker
I used a file called ckb_testdic.txt (containing the four words from your example sentence):

چۆنی
ئەتوانین
قسە
بکەین

and the command:
makeoxt -d ckb_testdic.txt -l "Central kurdish" -t rtl ckb CKspell.oxt

to create CKspell.oxt. 

Note that "kurdish" is spelled as in your original post (rather than "Kurdish").
I don't know if that is part of the issue or not, but I was trying to replicate what you reported.

(3) Optional -- check that word list was correctly processed
The .oxt file that is generated uses the .zip format. On other platforms (Linux for example) you can open the file directly to see what files are included. On Windows one can rename a copy of the file.

Make a copy of CKspell.oxt and rename to temp.zip.
NB: Windows will ask if you are sure you want to change the extension. Answer 'Yes'.
Double-click on the temp.zip file and Windows should open it.
Verify that there is a folder called "dictionaries" with a file "ckb.dic".
Verify that "ckb.dic" contains the words from the file ckb_testdic.txt (or whatever file was used to build the .oxt file).
Close the temp.zip file.
Delete temp.zip

(4) Installation of extension in LibreOffice writer (version 5.3 or later)
Use Tools menu, Extension Manager menu item.
In the dialog, click Add.
Navigate to the folder with the CKspell.oxt file.
Accept the license.
Close the Extension Manager dialog.
Note that you may need to restart LibreOffice at this point (and that any other LibreOffice files you have open will also be closed).

(5) First use of language in LibreOffice
The first time the language is used in LibreOffice, use the Format menu, Character menu item, and select the Font tab in the dialog.
From one of the "Language" drop-down lists, select the language name that was specified when the extension was created (the name after the "-l").

![image](https://user-images.githubusercontent.com/8562172/95242332-e2cc7780-07c3-11eb-8ea6-ac7a120200a9.png)

In the screenshot, "Central kurdish" (exactly as spelled in the command line above) appears.
You can also see other entries for "Kurdish, Central" from LibreOffice's built-in list.
Note that I'm using LibreOffice writer version 6.1.0.3. Other versions may look different.

After that the language should be available from the Tools menu, Language menu item.
In the screenshot, I selected "Central kurdish" for the selected text, which is the four-word sentence you gave plus a nonsense word (ببب).


![image](https://user-images.githubusercontent.com/8562172/95242478-14454300-07c4-11eb-937b-3606fd65727e.png)

(6) Check spelling
Using Tools, Spelling (or the F7 shortcut key), start the spell check.

![image](https://user-images.githubusercontent.com/8562172/95242585-38088900-07c4-11eb-8407-14123f532b00.png)

In the screenshot, you can see that the four words that are in the wordlist are not listed as misspelled.
The nonsense word I added is marked as "Not in dictionary" and the suggestion is the closest word
from the (very limited four-word) wordlist.

Further questions for investigation:
I don't know whether it is possible to specify a "Kurdish, Central" that matches one of the items in LibreOffice's built-in list with the result that your spell checker replaces the built-in one. Is that your goal? Or are you trying to get a spell checker for another variety of Central Kurdish?

At any rate, please let me know if the new version of makeoxt works for you and if this answers your question.

**Comment by jwtiyar** [comment]
Helllo
Thank you for great work and updating it to python 3.
First i have libreoffice 7.0.1, Because central kurdish is avaialable to libreoffice from version 7, My goal was when i install the central kurdish extension dictionary it automatically added to app language(built-in) which central kurdish not creating another language for same language.
As your screenshoot shows it did create new language called Central kurdish, Didn't merge with system language.
For check spelling first time i installed dictionary before two months maybe it was ok and everything works and it underlined the words that not exist in the dictionary that i created.
Now it creates the dictionary without any problem but i cant find it in the language bar, I dont't know what's my problem, your character shows 4 central kurdish but mine only one central kurdish which is system one when i did download libreoffice-ckb.

**Comment by n8marti** [comment]
I just opened a new issue with a related problem with the language Sango. It's already listed in the language list, but my spell check dictionary didn't get used if I set text to this language. The solution is that the language name in the dictionaries.xcu file should be like this: en_US, but makeoxt generates it using the 3-letter ISO code: eng. When I made that change and re-zipped the OXT file it works as expected.

**Comment by DavidLRowe** [comment]
@jwtiyar I'm not sure that it is possible to add to an existing dictionary.

@mhosken Does the list of language tags in makeoxt need to be updated for the version 7 release of LibreOffice?

**Comment by n8marti** [comment]
I feel like I'm kind of butting in here, but I think what @jwtiyar is saying is that he expects his spell check dictionary for ckb to be applied to the built-in language "Kurdish, Central (Iraq)" (or perhaps "Kurdish, Central (Iran)"?). It sounds like @DavidLRowe is saying there's already a built-in spell check dictionary for the built-in language, but I'm not seeing that in the screenshot; i.e. there's no "ab[check]" icon next to that built-in language. This to me sounds like what I ran into with Sango, and so I'm suggesting that when running the script @jwtiyar should use whatever the ISO 639-1 code LibreOffice has used for "Kurdish, Central (Iraq) or (Iran)", if one exists, like this:
```shell
makeoxt -d WordList.txt -l "Central kurdish" -t rtl <ISO 639-1 for Kurdish, Central (Iraq)> Central_Kurdish_Spellchecker.oxt
```
Otherwise he would need to find some other way to identify the language in his OXT file in the exact same way that LibreOffice identifies it internally, so that his spell check dictionary gets applied to the language he intends it to get applied to.

**Comment by DavidLRowe** [comment]
@n8marti Thanks for your comments. I've upgraded to version 7.1 (that is, v7.1.1.2 64-bit) in order to investigate further.
@jwtiyar Can you verify whether you are targeting sdh-Arab-IQ or sdh-Arab-IR? Thanks!

**Comment by jwtiyar** [comment]
> @n8marti Thanks for your comments. I've upgraded to version 7.1 (that is, v7.1.1.2 64-bit) in order to investigate further.
> @jwtiyar Can you verify whether you are targeting sdh-Arab-IQ or sdh-Arab-IR? Thanks!

Sorry guys for late reply.
Thank you for heloing me out, As @n8marti  said i expect lobreoffice to automaticallly add created .oxt to central kurdish language which available in the app but it's not, @DavidLRowe There is no exixting dictionary for central kurdish(iraq) neither central kurdish(iran), Dictioanry avaialble for Northern kurdish which are in syria and turkey.
Now i tested it again still not recognizing my added .oxt as central kurdish (iraq) dictionary.
@n8marti  ISO 639-1 just defined ku for all kurdish dialects, there is no ckb or kmr or sdh, But ISO 639-3 include it.
https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Languages/List_of_ISO_639-3_language_codes_(2019)

‌

**Comment by n8marti** [comment]
I think I've found the solution. WIth ckb you need to specify the country code (IQ or IR). @DavidLRowe's question above about sdh-Arab-IQ or sdh-Arab-IR gave me the idea:
```shell
makeoxt -d WordList.txt -l "Central kurdish (ckb-IQ)" -t rtl ckb-IQ Central_Kurdish_Spellchecker.oxt
```
After creating the extension with the above command and installing it, I was able to choose "Kurdish, Central (Iraq)" for the CTL Font Language in the Character menu:

![2021-03-12_Sélection_001](https://user-images.githubusercontent.com/23388501/110939059-1a23ef00-8335-11eb-9f32-af095fda415d.png)

**Comment by jwtiyar** [comment]
> makeoxt -d WordList.txt -l "Central kurdish (ckb-IQ)" -t rtl ckb-IQ Central_Kurdish_Spellchecker.oxt

Thank you very much, problem solved and automatically detected wrong texts and added to language in libreoffice.
Your help really asppreciated.

**Comment by jwtiyar** [comment]
> makeoxt -d WordList.txt -l "Central kurdish (ckb-IQ)" -t rtl ckb-IQ Central_Kurdish_Spellchecker.oxt

Thank you very much, problem solved and automatically detected wrong texts and added to language in libreoffice.
Your help really asppreciated.

**Comment by DavidLRowe** [comment]
Yes, thanks @n8marti
