### ISSUE TITLE
Error creating dictionary __init__() got an expected argument (punc)

### ISSUE THREAD

**Issue by jwtiyar** [silnrsi/oxttools#11]
Hey
I wanted to use makeoxt on windows installed everything as mentioned in readme.mk but when i want to create a dictionary it will give this output:
```

PS C:\Users\jwtiyar\Downloads\makeoxt> .\makeoxt -d hhh.txt -l "Central_Kurdish(ckb)" -t rtl ckb ckb-dict4.oxt
Traceback (most recent call last):
  File "makeoxt", line 180, in <module>
TypeError: __init__() got an unexpected keyword argument 'puncs'
Failed to execute script makeoxt
PS C:\Users\jwtiyar\Downloads\makeoxt>
```

What iam missing?

**Comment by DavidLRowe** [comment]
makeoxt has now been upgraded to Python 3, and a new makeoxt.exe created (so that Windows users don't have to build from source). 

If you still want to build makeoxt from source on Windows, please used the updated source follow the instructions. If you then have a problem, please raise a new issue. Thanks!
